dist: jammy

language: python
python:
  - "3.11"

before_install:
  - sudo apt-get update
  - sudo apt-get install libatlas-base-dev gfortran python-pip

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - pytest
  - coverage report --show-missing
  - pip install .
  - pip install .[dev]
  - pip install .[gui]

after_success:
  - curl -sL https://coveralls.io/coveralls-linux.tar.gz | tar -xz && ./coveralls
