dist: jammy

language: python
python:
  - "3.11"
cache: pip

before_install:
  - sudo apt-get update
  - sudo apt-get install libatlas-base-dev gfortran python-pip

install:
  - pip install -r requirements.txt
  - pip install coverage coveralls
  - pip install pytest pytest-cov

script:
  - pytest --cov-config .coveragerc --cov=pymote --cov-report=xml
  - coverage report --show-missing

after_success:
  - coveralls
