dist: jammy

language: python
python:
  - "3.11"
cache: pip

before_install:
  - sudo apt-get update
  - sudo apt-get install libatlas-base-dev gfortran python-pip

install:
  - pip install -r requirements.txt

script:
  - pytest
# - coverage run --source=pymote setup.py nosetests

after_success:
  - coveralls
# Force precise (Ubuntu 12.04) because of systemwide packages
# like PySide http://ebanshi.cc/questions/1415911/how-can-i-install-pyside-on-travis
# dist: precise
