dist: jammy

language: python
python:
  - "3.11"
cache: pip

before_install:
  - sudo apt-get update
  - sudo apt-get install libatlas-base-dev gfortran python-pip

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install pytest pytest-cov

script:
  - pytest
  - coverage report --show-missing
  - pip install .

after_success:
  - curl -sL https://coveralls.io/coveralls-linux.tar.gz | tar -xz && ./coveralls
